version: '3.7'
name: 'lazy-lab'
# ==================================
volumes:
# We cache pip so we dont need to populate it everytime
  pip-cache:

x-common:
  &common
  restart: on-failure
  logging:
    options:
      max-size: "5k"
      max-file: "2"

x-db-ready:
  &db-ready
  db:
    condition: service_healthy
    restart: true
# ==================================
services:
# ----------------------------------
  db:
    image: postgres:14-bullseye
    profiles:
      - essential
      - sdk
    healthcheck:
      test: ["CMD", "pg_isready", "||", "exit", "1"]
      interval: 5m30s
      timeout: 30s
      retries: 1
      start_period: 10s
    <<: *common
# ----------------------------------
  core:
    image: ${COMPOSE_PROJECT_NAME}-core
    build:
      args:
        - PYTHON_VERSION=3.11.3
      context: ./services/core-api
    profiles:
      - essential
      - sdk
    depends_on:
      <<: *db-ready
    <<: *common
# ----------------------------------
  ui:
    image: ${COMPOSE_PROJECT_NAME}-ui
    build:
      context: services/ui
    profiles:
      - essential
      - sdk
    restart: on-failure
    <<: *common
# ----------------------------------
  gateway:
    image: nginx:alpine
    depends_on:
      - core
      - ui
    profiles:
      - essential
      - sdk
    <<: *common
