version: '3.7'
name: 'lazy-lab'
# ==================================
volumes:
# We cache pip so we dont need to populate it everytime
  pip-cache:

x-common: 
    &common
    restart: on-failure
    logging:
      options:
        max-size: "5k"
        max-file: "2"
# ==================================
services:
# ----------------------------------
  db:
    image: postgres:14-bullseye
    profiles:
      - essential
      - sdk
    <<: *common
# ----------------------------------
  core:
    image: ${COMPOSE_PROJECT_NAME}-core
    build:
      args:
        - PYTHON_VERSION=3.10.6
      context: ./services/core-api
    profiles:
      - essential
      - sdk
    depends_on:
      - db
    <<: *common
# ----------------------------------
  ui:
    image: ${COMPOSE_PROJECT_NAME}-ui
    build:
      context: services/ui
    profiles:
      - essential
      - sdk
    restart: on-failure
    <<: *common
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "8085:8025"
  #   logging:
  #     driver: none

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - db
  #     - core
  #     - ui
  #   volumes:
  #     - ./services/ui/ten-school/public:/www/public
  #     - ./services/core-api/app/static:/www/public/static
  #     - ./services/nginx/dev.conf:/etc/nginx/nginx.conf:ro
