volumes:
# We cache pip so we dont need to populate it everytime
  lazy-lab-db-cache:
  firebase-cache:
  firebase-storage:

x-dev: &shared-dev
  restart: "no"
  env_file: ./@compose/envs/dev.env
  profiles:
    - dev

secrets:
  firebase-token:
    file: ./@compose/secrets/firebase.token
  firebase-project:
    file: ./@compose/secrets/firebase.project

services:
# -------------------------------------------------
  db:
    volumes:
      - lazy-lab-db-cache:/var/lib/postgresql/data
      - ./@compose/dev_data/db_init:/docker-entrypoint-initdb.d
    <<: *shared-dev
# -------------------------------------------------
  core:
    volumes:
      - ./services/core-api/app:/runtime/app
      - type: bind
        source: ./services/core-api/poetry.lock
        target: /runtime/poetry.lock
      - type: bind
        source: ./services/core-api/pyproject.toml
        target: /runtime/pyproject.toml
    ports:
      - "8000:8000"
    build:
      target: dev
    command: ./docker/container_bootstrap.sh python manage.py runserver 0.0.0.0:8000
    <<: *shared-dev
# -------------------------------------------------
  ui:
    volumes:
      - ./services/ui/lazy-lab:/runtime/app
    ports:
      - "9000:9000"
    command: yarn run dev --host 0.0.0.0 --port 9000
    <<: *shared-dev
# -------------------------------------------------
  gateway:
    ports:
      - "8080:80"
    volumes:
      - ./services/ui/lazy-lab/public:/www/public
      - ./services/core-api/app/static:/www/public/static
      - ./@compose/dev_data/gateway/dev.conf:/etc/nginx/nginx.conf:ro
    <<: *shared-dev
# -------------------------------------------------
  api-mock:
    image: ${COMPOSE_PROJECT_NAME}-mockoon
    build:
      args:
        - MOCKOON_VERSION=3.0.0
      context: ./@compose/dev_data/mockoon
    volumes:
      - ./@compose/dev_data/mockoon/runtime_data:/runtime_data
    <<: *shared-dev
# -------------------------------------------------
  firebase:
    image: ${COMPOSE_PROJECT_NAME}-firebase
    build:
      context: ./@compose/dev_data/firebase
    command: emulators:start
    secrets:
      - firebase-token
      - firebase-project
    ports:
      - "9080:9080"
      - "9081:9081"
      - "9082:9082"
      - "4900:4900"
    volumes:
      - ./@compose/dev_data/firebase/config:/runtime
      - firebase-cache:/root/.cache/firebase
      - firebase-storage:/tmp/firebase/storage
    <<: *shared-dev
